---

- block:
    - name: update
      raw: yum update

    - name: install epel-release (CentOS)
      raw: yum install -y epel-release

    - name: install python2
      raw: yum install -y python

  when: ansible_distribution == "CentOS"

- block:
    - name: update
      raw: apt-get update

    - name: install python2
      raw: apt-get install -y python

  when: ansible_distribution == "Ubuntu"
